# This is a basic workflow to help you get started with Actions

name: Test and Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, beta ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    name: Run tests, build and release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    # Install dependencies
    - name: Install dependencies
      run: npm ci
    # Run tests
    - name: Run tests
      run: npm test
    # Run prod build
    - name: Run tests and build
      run: npm run build
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm run semantic-release
